import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Used only if classic docs plugin remains; multi-instance sidebars are inline in config.
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
